<?php
namespace App\Console\Commands;
use Illuminate\Console\Command; 
use Illuminate\Support\Facades\Process;


// sessionRepository.save(session);

// return Result.success(session);

class AuthCrud extends Command
{
    /**  
     * The name and signature of the console command.
     *
     * @var string
     */ 
    //php artisan AuthCrud --user=admin --email=admin@email.com --password=1234 --seed=4
    protected $signature = 'AuthCrud {--user=} {--email=} {--password=} {--auth=} {--seed=}';
    /**
     * 
     * 
     * 
     * 
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Este comando crea un crud a partir del controller y model';
    /**
     * Execute the console command.
     */
    public function handle(){ 
        $userAdmin = $this->option('user');
        $emailAdmin = $this->option('email');
        $passwordAdmin = $this->option('password');
        $file = base_path()."\composer.json";
        header('Content-Type: text/plain');
        $contents = file_get_contents($file);
        $searchfor = 'spatie/laravel-permission';
        $pattern = preg_quote($searchfor, '/');
        $pattern = "/^.*$pattern.*\$/m";
        if (!preg_match_all($pattern, $contents, $matches))
        {
            Process::run('npm install');
            Process::run('composer update spatie/laravel-permission');
            $file = base_path()."\app\Http\.json";
            header('Content-Type: text/plain');
            $contents = file_get_contents($file);
            $searchfor = 'spatie/laravel-permission';
            $pattern = preg_quote($searchfor, '/');
            $pattern = "/^.*$pattern.*\$/m";
            if (!preg_match_all($pattern, $contents, $matches))
            {

            }
        } 
        $searchfor = 'laravel/breeze';
        $pattern = preg_quote($searchfor, '/');
        $pattern = "/^.*$pattern.*\$/m";
        if (!preg_match_all($pattern, $contents, $matches))
        {
            Process::run('composer require laravel/breeze --dev'); 
            Process::run('php artisan breeze:install');
             /**************** PUBLICAR EN EL VENDOR ****************************/
            Process::run('php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"');
            /**************************************************************************** */
        }  
        /*****************KERNEL*************************/
        $file_handle = fopen(base_path()."\app\Http\\Kernel.php", 'w');
        $data_to_write = '<?php'.PHP_EOL;
        $data_to_write .= 'namespace App\Http;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Foundation\Http\Kernel as HttpKernel;'.PHP_EOL;
        $data_to_write .= 'class Kernel extends HttpKernel'.PHP_EOL;
        $data_to_write .= '{'.PHP_EOL;
        $data_to_write .= '/**'.PHP_EOL;
        $data_to_write .= '* The application\'s global HTTP middleware stack.'.PHP_EOL;
        $data_to_write .= '*'.PHP_EOL;
        $data_to_write .= '* These middleware are run during every request to your application.'.PHP_EOL;
        $data_to_write .= '*'.PHP_EOL;
        $data_to_write .= '* @var array<int, class-string|string>'.PHP_EOL;
        $data_to_write .= '*/'.PHP_EOL;
        $data_to_write .= 'protected $middleware = ['.PHP_EOL;
        $data_to_write .= '// \App\Http\Middleware\TrustHosts::class,'.PHP_EOL;
        $data_to_write .= '\App\Http\Middleware\TrustProxies::class,'.PHP_EOL;
        $data_to_write .= '\Illuminate\Http\Middleware\HandleCors::class,'.PHP_EOL;
        $data_to_write .= '\App\Http\Middleware\PreventRequestsDuringMaintenance::class,'.PHP_EOL;
        $data_to_write .= '\Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,'.PHP_EOL;
        $data_to_write .= '\App\Http\Middleware\TrimStrings::class,'.PHP_EOL;
        $data_to_write .= '\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,'.PHP_EOL;
        $data_to_write .= '];'.PHP_EOL.PHP_EOL;
        $data_to_write .= '/**'.PHP_EOL;
        $data_to_write .= '* The application\'s route middleware groups'.PHP_EOL;
        $data_to_write .= '*'.PHP_EOL;
        $data_to_write .= '* @var array<string, array<int, class-string|string>>'.PHP_EOL;
        $data_to_write .= '*/'.PHP_EOL;
        $data_to_write .= 'protected $middlewareGroups = ['.PHP_EOL;
        $data_to_write .= ' \'web\' => ['.PHP_EOL;
        $data_to_write .= '    \App\Http\Middleware\EncryptCookies::class,'.PHP_EOL;
        $data_to_write .= '    \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,'.PHP_EOL;
        $data_to_write .= '    \Illuminate\Session\Middleware\StartSession::class,'.PHP_EOL;
        $data_to_write .= '    \Illuminate\View\Middleware\ShareErrorsFromSession::class,'.PHP_EOL;
        $data_to_write .= '    \App\Http\Middleware\VerifyCsrfToken::class,'.PHP_EOL;
        $data_to_write .= '    \Illuminate\Routing\Middleware\SubstituteBindings::class,'.PHP_EOL;
        $data_to_write .= ' ],'.PHP_EOL.PHP_EOL;; 
        $data_to_write .= '\'api\' => ['.PHP_EOL;
        $data_to_write .= '    // \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,'.PHP_EOL;
        $data_to_write .= '    \Illuminate\Routing\Middleware\ThrottleRequests::class.\':api\','.PHP_EOL;
        $data_to_write .= '    \Illuminate\Routing\Middleware\SubstituteBindings::class,'.PHP_EOL;
        $data_to_write .= '],'.PHP_EOL;
        $data_to_write .= '];'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '/**'.PHP_EOL;
        $data_to_write .= '* The application\'s middleware aliases.'.PHP_EOL;
        $data_to_write .= '*'.PHP_EOL;
        $data_to_write .= '* Aliases may be used instead of class names to conveniently assign middleware to routes and groups.'.PHP_EOL;
        $data_to_write .= '*'.PHP_EOL;
        $data_to_write .= '* @var array<string, class-string|string>'.PHP_EOL;
        $data_to_write .= '*/'.PHP_EOL;
        $data_to_write .= ' protected $middlewareAliases = ['.PHP_EOL;
        $data_to_write .= '  \'auth\' => \App\Http\Middleware\Authenticate::class,'.PHP_EOL;
        $data_to_write .= '  \'auth.basic\' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,'.PHP_EOL;
        $data_to_write .= '  \'auth.session\' => \Illuminate\Session\Middleware\AuthenticateSession::class,'.PHP_EOL;
        $data_to_write .= '  \'cache.headers\' => \Illuminate\Http\Middleware\SetCacheHeaders::class,'.PHP_EOL;
        $data_to_write .= '  \'can\' => \Illuminate\Auth\Middleware\Authorize::class,'.PHP_EOL;
        $data_to_write .= '  \'guest\' => \App\Http\Middleware\RedirectIfAuthenticated::class,'.PHP_EOL;
        $data_to_write .= '  \'password.confirm\' => \Illuminate\Auth\Middleware\RequirePassword::class,'.PHP_EOL;
        $data_to_write .= '  \'precognitive\' => \Illuminate\Foundation\Http\Middleware\HandlePrecognitiveRequests::class,'.PHP_EOL;
        $data_to_write .= '  \'signed\' => \App\Http\Middleware\ValidateSignature::class,'.PHP_EOL;
        $data_to_write .= '  \'throttle\' => \Illuminate\Routing\Middleware\ThrottleRequests::class,'.PHP_EOL;
        $data_to_write .= '  \'verified\' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,'.PHP_EOL;
        $data_to_write .= '  \'role_or_permission\' => \Spatie\Permission\Middlewares\RoleOrPermissionMiddleware::class,'.PHP_EOL;
        $data_to_write .= ' ];'.PHP_EOL;
        $data_to_write .= ' protected $routeMiddleware = [ '.PHP_EOL;
        $data_to_write .= '  \'role\' => \Spatie\Permission\Middlewares\RoleMiddleware::class,'.PHP_EOL;
        $data_to_write .= '  \'permission\' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,'.PHP_EOL;
        $data_to_write .= '  \'role_or_permission\' => \Spatie\Permission\Middlewares\RoleOrPermissionMiddleware::class,'.PHP_EOL;
        $data_to_write .= ' ];'.PHP_EOL;
        $data_to_write .= '}'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);    
        /**************************USER MIGRATIONS*****************/
        $file_handle = fopen(base_path()."\database\migrations\\2014_10_12_000000_create_users_table.php", 'w');
        $data_to_write = '<?php'.PHP_EOL; 
        $data_to_write .= 'use Illuminate\Database\Migrations\Migration;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Database\Schema\Blueprint;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Support\Facades\Schema;'.PHP_EOL.PHP_EOL;
        $data_to_write .= 'return new class extends Migration'.PHP_EOL;
        $data_to_write .= '{'.PHP_EOL;
        $data_to_write .= '/**'.PHP_EOL;
        $data_to_write .= '* Run the migrations.'.PHP_EOL;
        $data_to_write .= '*/'.PHP_EOL;
        $data_to_write .= ' public function up(): void'.PHP_EOL;
        $data_to_write .= ' {'.PHP_EOL;
        $data_to_write .= '    Schema::create(\'users\', function (Blueprint $table) {'.PHP_EOL;
        $data_to_write .= '       $table->id();'.PHP_EOL;   
        $data_to_write .= '       $table->string(\'name\')->nullable();'.PHP_EOL;       
        $data_to_write .= '       $table->string(\'username\')->unique();'.PHP_EOL; 
        $data_to_write .= '       $table->string(\'email\')->unique();'.PHP_EOL;    
        $data_to_write .= '       $table->timestamp(\'email_verified_at\')->nullable();'.PHP_EOL;   
        $data_to_write .= '       $table->string(\'password\');'.PHP_EOL;  
        $data_to_write .= '       $table->rememberToken();'.PHP_EOL;
        $data_to_write .= '       $table->timestamps();'.PHP_EOL;
        $data_to_write .= '    });'.PHP_EOL;
        $data_to_write .= ' }'.PHP_EOL;
        $data_to_write .= '/**'.PHP_EOL;
        $data_to_write .= '* Reverse the migrations.'.PHP_EOL; 
        $data_to_write .= '*/'.PHP_EOL; 
        $data_to_write .= ' public function down(): void'.PHP_EOL; 
        $data_to_write .= ' {'.PHP_EOL; 
        $data_to_write .= '   Schema::dropIfExists(\'users\');'.PHP_EOL;
        $data_to_write .= ' }'.PHP_EOL;   
        $data_to_write .= '};';     
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /************** Model user ******************/    
        $file_handle = fopen(base_path()."\app\Models\\User.php", 'w');
        $data_to_write = '<?php'.PHP_EOL;
        $data_to_write .= '  namespace App\Models;'.PHP_EOL;
        $data_to_write .= '  use Illuminate\Database\Eloquent\Factories\HasFactory;'.PHP_EOL;
        $data_to_write .= '  use Illuminate\Foundation\Auth\User as Authenticatable;'.PHP_EOL;
        $data_to_write .= '  use Illuminate\Notifications\Notifiable;'.PHP_EOL;
        $data_to_write .= '  use Laravel\Sanctum\HasApiTokens;'.PHP_EOL;
        $data_to_write .= '  use Spatie\Permission\Traits\HasRoles;'.PHP_EOL;
        $data_to_write .= ''.PHP_EOL;
        $data_to_write .= 'class User extends Authenticatable'.PHP_EOL;
        $data_to_write .= '{'.PHP_EOL;
        $data_to_write .= '    use HasApiTokens, HasFactory, Notifiable, HasRoles;'.PHP_EOL;
        $data_to_write .= '    /**'.PHP_EOL;
        $data_to_write .= '    * The attributes that are mass assignable.'.PHP_EOL;
        $data_to_write .= '    *'.PHP_EOL;
        $data_to_write .= '    * @var array<int, string>'.PHP_EOL;
        $data_to_write .= '    */'.PHP_EOL;
        $data_to_write .= '    protected $fillable = ['.PHP_EOL;
        $data_to_write .= "      'name',".PHP_EOL;
        $data_to_write .= "      'username',".PHP_EOL;
        $data_to_write .= "      'email',".PHP_EOL;
        $data_to_write .= "      'password',".PHP_EOL;
        $data_to_write .= '    ];'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '/**'.PHP_EOL.PHP_EOL;
        $data_to_write .= '* The attributes that should be hidden for serialization.'.PHP_EOL;
        $data_to_write .= '*'.PHP_EOL;;
        $data_to_write .= '* @var array<int, string>'.PHP_EOL;
        $data_to_write .= '*/'.PHP_EOL;
        $data_to_write .= '  protected $hidden = ['.PHP_EOL;;
        $data_to_write .= "   'password',".PHP_EOL;
        $data_to_write .= "   'remember_token',".PHP_EOL;
        $data_to_write .= '  ];'.PHP_EOL;
        $data_to_write .= ''.PHP_EOL;    
        $data_to_write .= '/**'.PHP_EOL;
        $data_to_write .= '* The attributes that should be cast.'.PHP_EOL;
        $data_to_write .= '*'.PHP_EOL;
        $data_to_write .= '* @var array<string, string>'.PHP_EOL;
        $data_to_write .= '*/'.PHP_EOL;
        $data_to_write .= '  protected $casts = ['.PHP_EOL;
        $data_to_write .= "    'email_verified_at' => 'datetime',".PHP_EOL;
        $data_to_write .= "    'password' => 'hashed',".PHP_EOL;
        $data_to_write .= '  ];'.PHP_EOL;
        $data_to_write .= '}'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /*************************** CONTROLLER ROL **********************************/
        $file_handle = fopen(base_path()."\app\Http\Controllers\\RoleController.php", 'w');
        $data_to_write = '<?php'.PHP_EOL.PHP_EOL; 
        $data_to_write .= 'namespace App\Http\Controllers;'.PHP_EOL.PHP_EOL; 
        $data_to_write .= 'use Illuminate\Http\Request;'.PHP_EOL;
        $data_to_write .= 'use App\Http\Controllers\Controller;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Support\Facades\DB;'.PHP_EOL;
        $data_to_write .= 'use Spatie\Permission\Models\Role;'.PHP_EOL;
        $data_to_write .= 'use Spatie\Permission\Models\Permission;'.PHP_EOL.PHP_EOL;  
        $data_to_write .= 'class RoleController extends Controller'.PHP_EOL;
        $data_to_write .= '{'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  function __construct()'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '        $this->middleware([\'permission:role-list|role-create|role-edit|role-delete\'], [\'only\' => [\'index\', \'store\']]);'.PHP_EOL;
        $data_to_write .= '        $this->middleware([\'permission:role-create\'], [\'only\' => [\'create\', \'store\']]);'.PHP_EOL;
        $data_to_write .= '        $this->middleware([\'permission:role-edit\'], [\'only\' => [\'edit\', \'update\']]);'.PHP_EOL;
        $data_to_write .= '        $this->middleware([\'permission:role-delete\'], [\'only\' => [\'destroy\']]);'.PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  public function index(Request $request)'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '            $roles = Role::orderBy(\'id\', \'DESC\')->paginate(5);'.PHP_EOL;
        $data_to_write .= '            return view(\'roles.index\', compact(\'roles\'));'.PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  public function create()'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '        $permission = Permission::get();'.PHP_EOL;
        $data_to_write .= "        return view('roles.create', compact('permission'));".PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL;
        $data_to_write .= '  public function store(Request $request)'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '        $this->validate($request, ['.PHP_EOL;
        $data_to_write .= "            'name' => 'required|unique:roles,name',".PHP_EOL;
        $data_to_write .= "            'permission' => 'required',".PHP_EOL;
        $data_to_write .= '        ]);'.PHP_EOL.PHP_EOL;
        $data_to_write .= '        $role = Role::create([\'name\' => $request->input(\'name\')]);'.PHP_EOL;
        $data_to_write .= '        $role->syncPermissions($request->input(\'permission\'));'.PHP_EOL.PHP_EOL;
        $data_to_write .= '        return redirect()->route(\'roles.index\')'.PHP_EOL;
        $data_to_write .= '            ->with(\'success\', \'Role created successfully\');'.PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL;
        $data_to_write .= '  public function show($id)'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '        $role = Role::find($id);'.PHP_EOL;
        $data_to_write .= '        $rolePermissions = Permission::join("role_has_permissions", "role_has_permissions.permission_id", "=", "permissions.id")'.PHP_EOL;
        $data_to_write .= '            ->where("role_has_permissions.role_id", $id)'.PHP_EOL;
        $data_to_write .= '            ->get();'.PHP_EOL.PHP_EOL; 
        $data_to_write .= "        return view('roles.show', compact('role', 'rolePermissions'));".PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL;
        $data_to_write .= '  public function edit($id)'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '        $role = Role::find($id);'.PHP_EOL;
        $data_to_write .= '        $permission = Permission::get();'.PHP_EOL;
        $data_to_write .= '        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id", $id)'.PHP_EOL;
        $data_to_write .= "            ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')".PHP_EOL;
        $data_to_write .= '            ->all();'.PHP_EOL.PHP_EOL; 
        $data_to_write .= "        return view('roles.edit', compact('role', 'permission', 'rolePermissions'));".PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  public function update(Request $request, $id)'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '        $this->validate($request, ['.PHP_EOL;
        $data_to_write .= "          'name' => 'required',".PHP_EOL;
        $data_to_write .= "          'permission' => 'required',".PHP_EOL;
        $data_to_write .= "        ]);".PHP_EOL.PHP_EOL; 
        $data_to_write .= '        $role = Role::find($id);'.PHP_EOL;
        $data_to_write .= '        $role->name = $request->input(\'name\');'.PHP_EOL;
        $data_to_write .= '        $role->save();'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '        $role->syncPermissions($request->input(\'permission\'));'.PHP_EOL;
        $data_to_write .= '        return redirect()->route(\'roles.index\')'.PHP_EOL;
        $data_to_write .= '             ->with(\'success\', \'Role updated successfully\');'.PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL;
        $data_to_write .= '  public function destroy($id)'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '         DB::table("roles")->where(\'id\', $id)->delete();'.PHP_EOL;
        $data_to_write .= '         return redirect()->route(\'roles.index\')'.PHP_EOL;
        $data_to_write .= '              ->with(\'success\', \'Role deleted successfully\');'.PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL;
        $data_to_write .= '}'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /************ Cargando el controller de user *****************/
        $file_handle = fopen(base_path()."\app\Http\Controllers\\UserController.php", 'w');
        $data_to_write = '<?php'.PHP_EOL.PHP_EOL; 
        $data_to_write .= 'namespace App\Http\Controllers;'.PHP_EOL.PHP_EOL; 
        $data_to_write .= 'use Illuminate\Http\Request;'.PHP_EOL;
        $data_to_write .= 'use App\Http\Controllers\Controller;'.PHP_EOL;
        $data_to_write .= 'use App\Models\User;'.PHP_EOL;
        $data_to_write .= 'use Spatie\Permission\Models\Role;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Support\Arr;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Support\Facades\DB;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Support\Facades\Hash;'.PHP_EOL.PHP_EOL;
        $data_to_write .= 'class UserController extends Controller'.PHP_EOL;
        $data_to_write .= '{'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  public function index(Request $request)'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '     $data = User::latest()->paginate(5);'.PHP_EOL;
        $data_to_write .= "     return view('users.index',compact('data'));".PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  public function create()'.PHP_EOL;
        $data_to_write .= '  {'.PHP_EOL;
        $data_to_write .= '     $roles = Role::pluck(\'name\',\'name\')->all();'.PHP_EOL;
        $data_to_write .= "     return view('users.create',compact('roles'));".PHP_EOL;
        $data_to_write .= "  }".PHP_EOL.PHP_EOL;
        $data_to_write .= '  public function store(Request $request)'.PHP_EOL;
        $data_to_write .= "  {".PHP_EOL;
        $data_to_write .= '     $this->validate($request, ['.PHP_EOL;
        $data_to_write .= "            'name' => 'required',".PHP_EOL;
        $data_to_write .= "            'username' => 'required',".PHP_EOL;
        $data_to_write .= "            'email' => 'required|email|unique:users,email',".PHP_EOL;
        $data_to_write .= "            'password' => 'required|same:confirm-password',".PHP_EOL;
        $data_to_write .= "            'roles' => 'required'".PHP_EOL;
        $data_to_write .= "     ]);".PHP_EOL.PHP_EOL;
        $data_to_write .= '     $input = $request->all();'.PHP_EOL.PHP_EOL;
        $data_to_write .= '     $input[\'password\'] = Hash::make($input[\'password\']);'.PHP_EOL;
        $data_to_write .= '     $user = User::create($input);'.PHP_EOL;
        $data_to_write .= '     $user->assignRole($request->input(\'roles\'));'.PHP_EOL;
        $data_to_write .= "     return redirect()->route('users.index')".PHP_EOL;
        $data_to_write .= "                      ->with('success','User created successfully');".PHP_EOL;
        $data_to_write .= " }".PHP_EOL.PHP_EOL; 
        $data_to_write .= ' public function show($id)'.PHP_EOL;
        $data_to_write .= ' {'.PHP_EOL; 
        $data_to_write .= '     $user = User::find($id);'.PHP_EOL;
        $data_to_write .= '     return view(\'users.show\',compact(\'user\'));'.PHP_EOL;
        $data_to_write .= ' }'.PHP_EOL.PHP_EOL;
        $data_to_write .= ' public function edit($id)'.PHP_EOL;
        $data_to_write .= ' {'.PHP_EOL;
        $data_to_write .= '     $user = User::find($id);'.PHP_EOL;
        $data_to_write .= '     $roles = Role::pluck(\'name\',\'name\')->all();'.PHP_EOL;
        $data_to_write .= '     $userRole = $user->roles->pluck(\'name\',\'name\')->all();'.PHP_EOL;
        $data_to_write .= '     return view(\'users.edit\',compact(\'user\',\'roles\',\'userRole\'));'.PHP_EOL;
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL;
        $data_to_write .= ' public function update(Request $request, $id)'.PHP_EOL;
        $data_to_write .= ' {'.PHP_EOL;
        $data_to_write .= '     $this->validate($request, ['.PHP_EOL;
        $data_to_write .= "             'name' => 'required',".PHP_EOL;
        $data_to_write .= "             'username' => 'required',".PHP_EOL;
        $data_to_write .= '             \'email\' => \'required|email|unique:users,email,\'.$id,'.PHP_EOL;
        $data_to_write .= "             'password' => 'same:confirm-password',".PHP_EOL;
        $data_to_write .= "             'roles' => 'required'".PHP_EOL;
        $data_to_write .= "     ]);".PHP_EOL.PHP_EOL;
        $data_to_write .= '     $input = $request->all();'.PHP_EOL;
        $data_to_write .= '     if(!empty($input[\'password\'])){ '.PHP_EOL;
        $data_to_write .= '        $input[\'password\'] = Hash::make($input[\'password\']);'.PHP_EOL;
        $data_to_write .= '     }else{'.PHP_EOL;
        $data_to_write .= '            $input = Arr::except($input,array(\'password\'));'.PHP_EOL;    
        $data_to_write .= '     }'.PHP_EOL.PHP_EOL;
        $data_to_write .= '     $user = User::find($id);'.PHP_EOL; 
        $data_to_write .= '     $user->update($input);'.PHP_EOL; 
        $data_to_write .= '     DB::table(\'model_has_roles\')->where(\'model_id\',$id)->delete();'.PHP_EOL; 
        $data_to_write .= '     $user->assignRole($request->input(\'roles\'));'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '     return redirect()->route(\'users.index\')'.PHP_EOL; 
        $data_to_write .= '     ->with(\'success\',\'User updated successfully\');'.PHP_EOL; 
        $data_to_write .= ' }'.PHP_EOL.PHP_EOL; 
        $data_to_write .= ' public function destroy($id)'.PHP_EOL.PHP_EOL; 
        $data_to_write .= ' {'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '     User::find($id)->delete();'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '     return redirect()->route(\'users.index\')'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '     ->with(\'success\',\'User deleted successfully\');'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  }'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '}'.PHP_EOL.PHP_EOL; 
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /**************SEEDER********************************************************/
        $file_handle = fopen(base_path()."\database\seeders\\RoleSeeder.php", 'w');
        $data_to_write = '<?php'.PHP_EOL.PHP_EOL; 
        $data_to_write .= 'namespace Database\Seeders;'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '// use Illuminate\Database\Console\Seeds\WithoutModelEvents;'.PHP_EOL.PHP_EOL;  
        $data_to_write .= 'use App\Models\User;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Database\Seeder;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Support\Facades\Hash;'.PHP_EOL;
        $data_to_write .= 'use Spatie\Permission\Models\Permission;'.PHP_EOL;
        $data_to_write .= 'use Spatie\Permission\Models\Role;'.PHP_EOL.PHP_EOL;  
        $data_to_write .= 'class RoleSeeder extends Seeder'.PHP_EOL;
        $data_to_write .= '{'.PHP_EOL.PHP_EOL;  
        $data_to_write .= '    /**'.PHP_EOL;
        $data_to_write .= '     * List of applications to add.'.PHP_EOL;
        $data_to_write .= '     */'.PHP_EOL;
        $data_to_write .= '    private $permissions = ['.PHP_EOL;
        $data_to_write .= "        'role-list',".PHP_EOL;
        $data_to_write .= "        'role-create',".PHP_EOL;
        $data_to_write .= "        'role-edit',".PHP_EOL;
        $data_to_write .= "        'role-delete',".PHP_EOL;
        $data_to_write .= "        'product-list',".PHP_EOL;
        $data_to_write .= "        'product-create',".PHP_EOL;
        $data_to_write .= "        'product-edit',".PHP_EOL;
        $data_to_write .= "        'product-delete'".PHP_EOL;
        $data_to_write .= '    ];'.PHP_EOL.PHP_EOL;   
        $data_to_write .= '    /**'.PHP_EOL;
        $data_to_write .= '     * Seed the application\'s database.'.PHP_EOL;
        $data_to_write .= '     */'.PHP_EOL;
        $data_to_write .= '    public function run(): void'.PHP_EOL;
        $data_to_write .= '    {'.PHP_EOL;
        $data_to_write .= '        foreach ($this->permissions as $permission) {'.PHP_EOL;
        $data_to_write .= '            Permission::create([\'name\' => $permission]);'.PHP_EOL;
        $data_to_write .= '    }'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '        // Create admin User and assign the role to him.'.PHP_EOL;
        $data_to_write .= '        $user = User::create(['.PHP_EOL;  
        $data_to_write .= "            'username' => '$userAdmin',".PHP_EOL;
        $data_to_write .= "            'email' => '$emailAdmin',".PHP_EOL;
        $data_to_write .= "            'password' => Hash::make('$passwordAdmin')".PHP_EOL;
        $data_to_write .= "        ]);".PHP_EOL.PHP_EOL; 
        $data_to_write .= '        $role = Role::create([\'name\' => \'Admin\']);'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '        $role = Role::create([\'name\' => \'User\']);'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '        $permissions = Permission::pluck(\'id\', \'id\')->all();'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '        $role->syncPermissions($permissions);'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '        $user->assignRole([$role->id]);'.PHP_EOL.PHP_EOL;
        $data_to_write .= '    }'.PHP_EOL;
        $data_to_write .= '}'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /***************************************************************************/
        /************************* BLADE **************************************/
        /**************BLADE MASTER************************************/
        $ruta_views =  base_path()."\\resources\\views\\layouts\\";
        if (!file_exists($ruta_views)) {
            mkdir($ruta_views, 0700); //creando directorio para las vistas
        }
        $file_handle = fopen(base_path()."\\resources\\views\\layouts\\master.blade.php", 'w');
        $data_to_write = '<!DOCTYPE html>'.PHP_EOL;
        $data_to_write .= '<html lang="{{ app()->getLocale() }}">'.PHP_EOL;
        $data_to_write .= '<head>'.PHP_EOL;
        $data_to_write .= '    <meta charset="utf-8">'.PHP_EOL;
        $data_to_write .= '    <meta http-equiv="X-UA-Compatible" content="IE=edge">'.PHP_EOL;
        $data_to_write .= '    <meta name="viewport" content="width=device-width, initial-scale=1">'.PHP_EOL;
        $data_to_write .= '    <meta name="csrf-token" content="{{ csrf_token() }}">'.PHP_EOL;
        $data_to_write .= '    <title>{{env(\'APP_NAME\')}}</title>'.PHP_EOL;
        $data_to_write .= '    <script src="{{ asset(\'js/app.js\') }}" defer></script>'.PHP_EOL;
        $data_to_write .= '    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">'.PHP_EOL;
        $data_to_write .= '    <link href="{{ asset(\'css/app.css\') }}" rel="stylesheet">'.PHP_EOL;
        $data_to_write .= '</head>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '<body>'.PHP_EOL;
        $data_to_write .= '    <div id="app">'.PHP_EOL;
        $data_to_write .= '        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">'.PHP_EOL;
        $data_to_write .= '            <div class="container">'.PHP_EOL;
        $data_to_write .= '                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">'.PHP_EOL;
        $data_to_write .= '                    <span class="navbar-toggler-icon"></span>'.PHP_EOL;
        $data_to_write .= '                </button>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '                <div class="collapse navbar-collapse" id="navbarSupportedContent">'.PHP_EOL;
        $data_to_write .= '                    <ul class="navbar-nav ms-auto">'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '                        @guest'.PHP_EOL;
        $data_to_write .= '                            <li><a class="nav-link" href="{{ route(\'login\') }}">{{ (\'Login\') }} </a></li>'.PHP_EOL;
        $data_to_write .= '                            <li><a class="nav-link" href="{{ route(\'register\') }}">{{ (\'Register\') }}</a></li>'.PHP_EOL;
        $data_to_write .= '                        @else'.PHP_EOL;
        $data_to_write .= '                            <li><a class="nav-link" href="{{ route(\'users.index\') }}">Manage Users</a></li>'.PHP_EOL;
        $data_to_write .= '                            <li><a class="nav-link" href="{{ route(\'roles.index\') }}">Manage Role</a></li> '.PHP_EOL;
        $data_to_write .= '                            <li class="ms-3 nav-item dropdown">'.PHP_EOL;
        $data_to_write .= '                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>'.PHP_EOL;
        $data_to_write .= '                                    {{ Auth::user()->name }} <span class="caret"></span>'.PHP_EOL;
        $data_to_write .= '                                </a>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">'.PHP_EOL;
        $data_to_write .= '                                    <a class="dropdown-item" href="{{ route(\'logout\') }}"'.PHP_EOL;
        $data_to_write .= '                                       onclick="event.preventDefault();'.PHP_EOL;
        $data_to_write .= '                                                     document.getElementById(\'logout-form\').submit();">'.PHP_EOL;
        $data_to_write .= '                                        {{ (\'Logout\') }}'.PHP_EOL;
        $data_to_write .= '                                    </a>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '                                    <form id="logout-form" action="{{ route(\'logout\') }}" method="POST" style="display: none;">'.PHP_EOL;
        $data_to_write .= '                                        @csrf'.PHP_EOL;
        $data_to_write .= '                                    </form>'.PHP_EOL;
        $data_to_write .= '                                </div>'.PHP_EOL;
        $data_to_write .= '                            </li>'.PHP_EOL;
        $data_to_write .= '                        @endguest'.PHP_EOL;
        $data_to_write .= '                    </ul>'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </nav>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '        <main class="py-4 bg-light">'.PHP_EOL;
        $data_to_write .= '            <div class="container">'.PHP_EOL;
        $data_to_write .= '            @yield(\'content\')'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </main>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL;
        $data_to_write .= '</body>'.PHP_EOL;
        $data_to_write .= '</html> '.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /****************USERS************************/
        $ruta_views =  base_path()."\\resources\\views\\users\\";
        if (!file_exists($ruta_views)) {
            mkdir($ruta_views, 0700); //creando directorio para las vistas
        }
        /***************index********************************/
        $file_handle = fopen(base_path()."\\resources\\views\\users\\index.blade.php", 'w'); 
        $data_to_write = '@extends(\'layouts.master\')'.PHP_EOL;
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '<div class="row">'.PHP_EOL;
        $data_to_write .= ' <div class="col-lg-12 margin-tb mb-4">'.PHP_EOL;
        $data_to_write .= '  <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '    <h2>Users Management'.PHP_EOL;                
        $data_to_write .= '     <div class="float-end">'.PHP_EOL;
        $data_to_write .= '         <a class="btn btn-success" href="{{ route(\'users.create\') }}"> Create New User</a>'.PHP_EOL;
        $data_to_write .= '     </div>'.PHP_EOL;
        $data_to_write .= '    </h2>'.PHP_EOL;
        $data_to_write .= '  </div>'.PHP_EOL;
        $data_to_write .= ' </div>'.PHP_EOL;
        $data_to_write .= '</div>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@if ($message = Session::get(\'success\'))'.PHP_EOL;
        $data_to_write .= '<div class="alert alert-success my-2">'.PHP_EOL;
        $data_to_write .= ' <p>{{ $message }}</p>'.PHP_EOL;
        $data_to_write .= '</div>'.PHP_EOL;
        $data_to_write .= '@endif'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '<table class="table table-bordered table-hover table-striped">'.PHP_EOL;
        $data_to_write .= ' <tr>'.PHP_EOL;
        $data_to_write .= '   <th>Name</th>'.PHP_EOL;
        $data_to_write .= '   <th>Email</th>'.PHP_EOL;
        $data_to_write .= '   <th>Roles</th>'.PHP_EOL;
        $data_to_write .= '   <th width="280px">Action</th>'.PHP_EOL;
        $data_to_write .= ' </tr>'.PHP_EOL;
        $data_to_write .= '@foreach ($data as $key => $user)'.PHP_EOL;
        $data_to_write .= ' <tr>'.PHP_EOL;
        $data_to_write .= '  <td>{{ $user->name }}</td>'.PHP_EOL;
        $data_to_write .= '  <td>{{ $user->email }}</td>'.PHP_EOL;
        $data_to_write .= '  <td>'.PHP_EOL;
        $data_to_write .= '   @if(!empty($user->getRoleNames()))'.PHP_EOL;
        $data_to_write .= '    @foreach($user->getRoleNames() as $v)'.PHP_EOL;
        $data_to_write .= '     <label class="badge badge-secondary text-dark">{{ $v }}</label>'.PHP_EOL;
        $data_to_write .= '    @endforeach'.PHP_EOL;
        $data_to_write .= '   @endif'.PHP_EOL;
        $data_to_write .= '  </td>'.PHP_EOL;
        $data_to_write .= '  <td>'.PHP_EOL;
        $data_to_write .= '    <a class="btn btn-info" href="{{ route(\'users.show\',$user->id) }}">Show</a>'.PHP_EOL;
        $data_to_write .= '    <a class="btn btn-primary" href="{{ route(\'users.edit\',$user->id) }}">Edit</a>'.PHP_EOL;
        $data_to_write .= '    <a class="btn btn-success" href="{{ route(\'users.destroy\',$user->id) }}"> Delete</a>'.PHP_EOL;
        $data_to_write .= '  </td>'.PHP_EOL;
        $data_to_write .= ' </tr>'.PHP_EOL;
        $data_to_write .= '@endforeach'.PHP_EOL;
        $data_to_write .= '</table>'.PHP_EOL;
        $data_to_write .= '@endsection '.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /*************************create*****************************************/
        $file_handle = fopen(base_path()."\\resources\\views\users\\create.blade.php", 'w'); 
        $data_to_write = '@extends(\'layouts.master\')'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '    <div class="row">'.PHP_EOL;
        $data_to_write .= '        <div class="col-lg-12 margin-tb mb-4">'.PHP_EOL;
        $data_to_write .= '            <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '                <h2>Create New User'.PHP_EOL;
        $data_to_write .= '                    <div class="float-end">'.PHP_EOL;
        $data_to_write .= '                        <a class="btn btn-primary" href="{{ route(\'users.index\') }}"> Back</a>'.PHP_EOL;
        $data_to_write .= '                    </div>'.PHP_EOL;
        $data_to_write .= '                </h2>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    @if (count($errors) > 0)'.PHP_EOL;
        $data_to_write .= '        <div class="alert alert-danger">'.PHP_EOL;
        $data_to_write .= '            <strong>Whoops!</strong> There were some problems with your input.<br><br>'.PHP_EOL;
        $data_to_write .= '            <ul>'.PHP_EOL;
        $data_to_write .= '                @foreach ($errors->all() as $error)'.PHP_EOL;
        $data_to_write .= '                    <li>{{ $error }}</li>'.PHP_EOL;
        $data_to_write .= '                @endforeach'.PHP_EOL;
        $data_to_write .= '            </ul>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    @endif'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    <form action="{{ route(\'users.store\') }}" method="POST">'.PHP_EOL;
        $data_to_write .= '        @csrf'.PHP_EOL;
        $data_to_write .= '        <div class="row">'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Name:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="text" name="name" class="form-control" placeholder="Name">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Email:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="email" name="email" class="form-control" placeholder="Email">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Password:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="password" name="password" class="form-control" placeholder="Password">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Confirm Password:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="password" name="confirm-password" class="form-control" placeholder="Confirm Password">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Role:</strong>'.PHP_EOL;
        $data_to_write .= '                    <select class="form-control multiple" multiple name="roles[]">'.PHP_EOL;
        $data_to_write .= '                        @foreach ($roles as $role)'.PHP_EOL;
        $data_to_write .= '                            <option value="{{ $role }}">{{ $role }}</option>'.PHP_EOL;
        $data_to_write .= '                        @endforeach'.PHP_EOL;
        $data_to_write .= '                    </select>'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3 text-center">'.PHP_EOL;
        $data_to_write .= '                <button type="submit" class="btn btn-primary">Submit</button>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </form>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@endsection'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /*********************************show********************************/
        $file_handle = fopen(base_path()."\\resources\\views\\users\\show.blade.php", 'w'); 
        $data_to_write = '@extends(\'layouts.master\') '.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '<div class="row">'.PHP_EOL;
        $data_to_write .= '    <div class="col-lg-12 margin-tb mb-4">'.PHP_EOL;
        $data_to_write .= '        <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '            <h2>Show User</h2>'.PHP_EOL;
        $data_to_write .= '            <div class="float-end">'.PHP_EOL;
        $data_to_write .= '                <a class="btn btn-primary" href="{{ route(\'users.index\') }}"> Back</a>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL;
        $data_to_write .= '</div> '.PHP_EOL.PHP_EOL; 
        $data_to_write .= '<div class="row">'.PHP_EOL;
        $data_to_write .= '    <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '        <div class="form-group">'.PHP_EOL;
        $data_to_write .= '            <strong>Name:</strong>'.PHP_EOL;
        $data_to_write .= '            {{ $user->name }}'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL;
        $data_to_write .= '    <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '        <div class="form-group">'.PHP_EOL;
        $data_to_write .= '            <strong>Email:</strong>'.PHP_EOL;
        $data_to_write .= '            {{ $user->email }}'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL;
        $data_to_write .= '    <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '        <div class="form-group">'.PHP_EOL;
        $data_to_write .= '            <strong>Roles:</strong>'.PHP_EOL;
        $data_to_write .= '            @if(!empty($user->getRoleNames()))'.PHP_EOL;
        $data_to_write .= '                @foreach($user->getRoleNames() as $v)'.PHP_EOL;
        $data_to_write .= '                    <label class="badge badge-secondary text-dark">{{ $v }}</label>'.PHP_EOL;
        $data_to_write .= '                @endforeach'.PHP_EOL;
        $data_to_write .= '            @endif'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL;
        $data_to_write .= '</div>'.PHP_EOL;
        $data_to_write .= '@endsection '.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /*************************edit*************************************/
        $file_handle = fopen(base_path()."\\resources\\views\\users\\edit.blade.php", 'w');  
        $data_to_write = '@extends(\'layouts.master\') '.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '    <div class="row">'.PHP_EOL;
        $data_to_write .= '        <div class="col-lg-12 margin-tb mb-4">'.PHP_EOL;
        $data_to_write .= '            <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '                <h2>Edit User'.PHP_EOL;
        $data_to_write .= '                    <div class="float-end">'.PHP_EOL;
        $data_to_write .= '                        <a class="btn btn-primary" href="{{ route(\'users.index\') }}"> Back</a>'.PHP_EOL;
        $data_to_write .= '                    </div>'.PHP_EOL;
        $data_to_write .= '                </h2>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    @if (count($errors) > 0)'.PHP_EOL;
        $data_to_write .= '        <div class="alert alert-danger">'.PHP_EOL;
        $data_to_write .= '            <strong>Whoops!</strong> There were some problems with your input.<br><br>'.PHP_EOL;
        $data_to_write .= '            <ul>'.PHP_EOL;
        $data_to_write .= '                @foreach ($errors->all() as $error)'.PHP_EOL;
        $data_to_write .= '                    <li>{{ $error }}</li>'.PHP_EOL;
        $data_to_write .= '                @endforeach'.PHP_EOL;
        $data_to_write .= '            </ul>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    @endif'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    <form action="{{ route(\'users.update\', $user->id) }}" method="PATCH">'.PHP_EOL;
        $data_to_write .= '        @csrf'.PHP_EOL;
        $data_to_write .= '        <div class="row">'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Name:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="text" value="{{ $user->name }}" name="name" class="form-control"'.PHP_EOL;
        $data_to_write .= '                        placeholder="Name">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Email:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="email" name="email" value="{{ $user->email }}" class="form-control"'.PHP_EOL;
        $data_to_write .= '                        placeholder="Email">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Password:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="password" name="password" class="form-control"'.PHP_EOL;
        $data_to_write .= '                        placeholder="Password">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Confirm Password:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="password" name="confirm-password" class="form-control"'.PHP_EOL;
        $data_to_write .= '                        placeholder="Confirm Password">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Role:</strong>'.PHP_EOL;
        $data_to_write .= '                    <select class="form-control multiple" multiple name="roles[]">'.PHP_EOL;
        $data_to_write .= '                        @foreach ($roles as $role)'.PHP_EOL;
        $data_to_write .= '                            <option value="{{ $role }}">{{ $role }}</option>'.PHP_EOL;
        $data_to_write .= '                        @endforeach'.PHP_EOL;
        $data_to_write .= '                    </select>'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3 text-center">'.PHP_EOL;
        $data_to_write .= '                <button type="submit" class="btn btn-primary">Submit</button>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </form>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@endsection'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /******************************BLADE ROLE***************************************************/
        $ruta_views =  base_path()."\\resources\\views\\roles\\";
        if (!file_exists($ruta_views)) {
            mkdir($ruta_views, 0700); //creando directorio para las vistas
        }
        /***********************index*********************/
        $file_handle = fopen(base_path()."\\resources\\views\\roles\\index.blade.php", 'w');  
        $data_to_write = '@extends(\'layouts.master\')'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '    <div class="row">'.PHP_EOL;
        $data_to_write .= '        <div class="col-lg-12 margin-tb mb-4">'.PHP_EOL;
        $data_to_write .= '            <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '                <h2>Role Management'.PHP_EOL;
        $data_to_write .= '                    <div class="float-end">'.PHP_EOL;
        $data_to_write .= '                        @can(\'role-create\')'.PHP_EOL;
        $data_to_write .= '                            <a class="btn btn-success" href="{{ route(\'roles.create\') }}"> Create New Role</a>'.PHP_EOL;
        $data_to_write .= '                        @endcan'.PHP_EOL;
        $data_to_write .= '                    </div>'.PHP_EOL;
        $data_to_write .= '                </h2>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    @if ($message = Session::get(\'success\'))'.PHP_EOL;
        $data_to_write .= '        <div class="alert alert-success">'.PHP_EOL;
        $data_to_write .= '            <p>{{ $message }}</p>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    @endif'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    <table class="table table-striped table-hover">'.PHP_EOL;
        $data_to_write .= '        <tr>'.PHP_EOL;
        $data_to_write .= '            <th>Name</th>'.PHP_EOL;
        $data_to_write .= '            <th width="280px">Action</th>'.PHP_EOL;
        $data_to_write .= '        </tr>'.PHP_EOL;
        $data_to_write .= '        @foreach ($roles as $key => $role)'.PHP_EOL;
        $data_to_write .= '            <tr>'.PHP_EOL;
        $data_to_write .= '                <td>{{ $role->name }}</td>'.PHP_EOL;
        $data_to_write .= '                <td>'.PHP_EOL;
        $data_to_write .= '                    <form action="{{ route(\'roles.destroy\', $role->id) }}" method="POST">'.PHP_EOL;
        $data_to_write .= '                        <a class="btn btn-info" href="{{ route(\'roles.show\', $role->id) }}">Show</a>'.PHP_EOL;
        $data_to_write .= '                        @can(\'role-edit\')'.PHP_EOL;
        $data_to_write .= '                            <a class="btn btn-primary" href="{{ route(\'roles.edit\', $role->id) }}">Edit</a>'.PHP_EOL;
        $data_to_write .= '                        @endcan'.PHP_EOL;
        $data_to_write .= '                        @csrf'.PHP_EOL;
        $data_to_write .= '                        @method(\'DELETE\')'.PHP_EOL;
        $data_to_write .= '                        @can(\'product-delete\')'.PHP_EOL;
        $data_to_write .= '                            <button type="submit" class="btn btn-danger">Delete</button>'.PHP_EOL;
        $data_to_write .= '                        @endcan'.PHP_EOL;
        $data_to_write .= '                    </form>'.PHP_EOL;
        $data_to_write .= '                </td>'.PHP_EOL;
        $data_to_write .= '            </tr>'.PHP_EOL;
        $data_to_write .= '        @endforeach'.PHP_EOL;
        $data_to_write .= '    </table>'.PHP_EOL.PHP_EOL;  
        $data_to_write .= '    {!! $roles->render() !!}'.PHP_EOL;
        $data_to_write .= '@endsection'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /*******************************show roles***************************************/
        $file_handle = fopen(base_path()."\\resources\\views\\roles\\show.blade.php", 'w');  
        $data_to_write = '@extends(\'layouts.master\')'.PHP_EOL.PHP_EOL;
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '    <div class="row">'.PHP_EOL;
        $data_to_write .= '        <div class="col-lg-12 margin-tb mb-4">'.PHP_EOL;
        $data_to_write .= '            <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '                <h2> Show Role'.PHP_EOL;
        $data_to_write .= '                    <div class="float-end">'.PHP_EOL;
        $data_to_write .= '                        <a class="btn btn-primary" href="{{ route(\'roles.index\') }}"> Back</a>'.PHP_EOL;
        $data_to_write .= '                    </div>'.PHP_EOL;
        $data_to_write .= '                </h2>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL.PHP_EOL;
        $data_to_write .= '    <div class="row">'.PHP_EOL;
        $data_to_write .= '        <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '            <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                <strong>Name:</strong>'.PHP_EOL;
        $data_to_write .= '                {{ $role->name }}'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '        <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '            <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                <strong>Permissions:</strong>'.PHP_EOL;
        $data_to_write .= '                @if (!empty($rolePermissions))'.PHP_EOL;
        $data_to_write .= '                    @foreach ($rolePermissions as $v)'.PHP_EOL;
        $data_to_write .= '                        <label class="label label-secondary text-dark">{{ $v->name }},</label>'.PHP_EOL;
        $data_to_write .= '                    @endforeach'.PHP_EOL;
        $data_to_write .= '                @endif'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL;
        $data_to_write .= '@endsection'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /*************************************create****************************************************/
        $file_handle = fopen(base_path()."\\resources\\views\\roles\\create.blade.php", 'w');  
        $data_to_write = '@extends(\'layouts.master\')'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '    <div class="row">'.PHP_EOL;
        $data_to_write .= '        <div class="col-lg-12 margin-tb mb-4">'.PHP_EOL;
        $data_to_write .= '            <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '                <h2>Create New Role'.PHP_EOL;
        $data_to_write .= '                    <div class="float-end">'.PHP_EOL;
        $data_to_write .= '                        <a class="btn btn-primary" href="{{ route(\'roles.index\') }}"> Back</a>'.PHP_EOL;
        $data_to_write .= '                    </div>'.PHP_EOL;
        $data_to_write .= '                </h2>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    @if (count($errors) > 0)'.PHP_EOL;
        $data_to_write .= '        <div class="alert alert-danger">'.PHP_EOL;
        $data_to_write .= '            <strong>Whoops!</strong> There were some problems with your input.<br><br>'.PHP_EOL;
        $data_to_write .= '            <ul>'.PHP_EOL;
        $data_to_write .= '                @foreach ($errors->all() as $error)'.PHP_EOL;
        $data_to_write .= '                    <li>{{ $error }}</li>'.PHP_EOL;
        $data_to_write .= '                @endforeach'.PHP_EOL;
        $data_to_write .= '            </ul>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    @endif'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    <form action="{{ route(\'roles.store\') }}" method="POST">'.PHP_EOL;
        $data_to_write .= '        @csrf'.PHP_EOL;
        $data_to_write .= '        <div class="row">'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 col-sm-12 col-md-12">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Name:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="text" name="name" class="form-control" placeholder="Name">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 col-sm-12 col-md-12">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Permission:</strong>'.PHP_EOL;
        $data_to_write .= '                    <br />'.PHP_EOL;
        $data_to_write .= '                    @foreach ($permission as $value)'.PHP_EOL;
        $data_to_write .= '                        <label>'.PHP_EOL;
        $data_to_write .= '                            <input type="checkbox" name="permission[]" value="{{ $value->id }}" class="name">'.PHP_EOL;
        $data_to_write .= '                            {{ $value->name }}</label>'.PHP_EOL;
        $data_to_write .= '                        <br />'.PHP_EOL;
        $data_to_write .= '                    @endforeach'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 col-sm-12 col-md-12 text-center">'.PHP_EOL;
        $data_to_write .= '                <button type="submit" class="btn btn-primary">Submit</button>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </form>'.PHP_EOL;
        $data_to_write .= '@endsection'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /************************************edit*******************************************************/
        $file_handle = fopen(base_path()."\\resources\\views\\roles\\edit.blade.php", 'w');  
        $data_to_write = '@extends(\'layouts.master\')'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '@section(\'content\')'.PHP_EOL;
        $data_to_write .= '    <div class="row">'.PHP_EOL;
        $data_to_write .= '        <div class="col-lg-12 margin-tb">'.PHP_EOL;
        $data_to_write .= '            <div class="pull-left">'.PHP_EOL;
        $data_to_write .= '                <h2>Edit Role'.PHP_EOL;
        $data_to_write .= '                    <div class="float-end">'.PHP_EOL;
        $data_to_write .= '                        <a class="btn btn-primary" href="{{ route(\'roles.index\') }}"> Back</a>'.PHP_EOL;
        $data_to_write .= '                    </div>'.PHP_EOL;
        $data_to_write .= '                </h2>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL.PHP_EOL;  
        $data_to_write .= '    @if (count($errors) > 0)'.PHP_EOL;
        $data_to_write .= '        <div class="alert alert-danger">'.PHP_EOL;
        $data_to_write .= '            <strong>Whoops!</strong> There were some problems with your input.<br><br>'.PHP_EOL;
        $data_to_write .= '            <ul>'.PHP_EOL;
        $data_to_write .= '                @foreach ($errors->all() as $error)'.PHP_EOL;
        $data_to_write .= '                    <li>{{ $error }}</li>'.PHP_EOL;
        $data_to_write .= '                @endforeach'.PHP_EOL;
        $data_to_write .= '            </ul>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    @endif'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '    <form action="{{ route(\'roles.update\', $role->id) }}" method="PATCH">'.PHP_EOL;
        $data_to_write .= '        @csrf'.PHP_EOL;
        $data_to_write .= '        <div class="row">'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Name:</strong>'.PHP_EOL;
        $data_to_write .= '                    <input type="text" value="{{ $role->name }}" name="name" class="form-control"'.PHP_EOL;
        $data_to_write .= '                        placeholder="Name">'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3">'.PHP_EOL;
        $data_to_write .= '                <div class="form-group">'.PHP_EOL;
        $data_to_write .= '                    <strong>Permission:</strong>'.PHP_EOL;
        $data_to_write .= '                    <br />'.PHP_EOL;
        $data_to_write .= '                    @foreach ($permission as $value)'.PHP_EOL;
        $data_to_write .= '                        <label>'.PHP_EOL;
        $data_to_write .= '                            <input type="checkbox" @if (in_array($value->id, $rolePermissions)) checked @endif name="permission[]"'.PHP_EOL;
        $data_to_write .= '                                value="{{ $value->id }}" class="name">'.PHP_EOL;
        $data_to_write .= '                            {{ $value->name }}</label>'.PHP_EOL;
        $data_to_write .= '                        <br />'.PHP_EOL;
        $data_to_write .= '                    @endforeach'.PHP_EOL;
        $data_to_write .= '                </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <div class="col-xs-12 mb-3 text-center">'.PHP_EOL;
        $data_to_write .= '                <button type="submit" class="btn btn-primary">Submit</button>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </form>'.PHP_EOL.PHP_EOL;
        $data_to_write .= '@endsection'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /***********************ROUTES********************************************************************/
        $file_handle = fopen(base_path()."\\routes\\auth_users.php", 'w'); 
        $data_to_write = '<?php'.PHP_EOL;
        $data_to_write .= 'Route::get(\'/dashboard\', function () {'.PHP_EOL;
        $data_to_write .= '    return view(\'dashboard\');'.PHP_EOL;
        $data_to_write .= '})->middleware([\'auth\', \'verified\'])->name(\'dashboard\');'.PHP_EOL.PHP_EOL;
        $data_to_write .= 'Route::middleware(\'auth\')->group(function () {'.PHP_EOL;
        $data_to_write .= '    Route::get(\'/profile\', [ProfileController::class, \'edit\'])->name(\'profile.edit\');'.PHP_EOL;
        $data_to_write .= '    Route::patch(\'/profile\', [ProfileController::class, \'update\'])->name(\'profile.update\');'.PHP_EOL;
        $data_to_write .= '    Route::delete(\'/profile\', [ProfileController::class, \'destroy\'])->name(\'profile.destroy\');'.PHP_EOL;
        $data_to_write .= '    // Our resource routes'.PHP_EOL;
        $data_to_write .= '    Route::resource(\'roles\', App\Http\Controllers\RoleController::class);'.PHP_EOL;
        $data_to_write .= '    Route::resource(\'users\', App\Http\Controllers\UserController::class);'.PHP_EOL; 
        $data_to_write .= '});'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /************************* AÑADIR RUTA ************************************************************/ 
        $data_route = 'require __DIR__'.".'\\auth_users.php';";
        $file_route = base_path()."\\routes\\web.php";

        if( strpos(file_get_contents($file_route),$data_route) !== false) {
            file_put_contents($file_route, str_replace($data_route , $data_route, file_get_contents($file_route)));
        }else {
            file_put_contents($file_route,file_get_contents($file_route).PHP_EOL.PHP_EOL.$data_route);
        }
        /*************************************************************************************************/
        $file_handle = fopen(base_path()."\\database\\seeders\\DatabaseSeeder.php", 'w'); 
        $data_to_write = '<?php'.PHP_EOL.PHP_EOL; 
        $data_to_write .= 'namespace Database\Seeders;'.PHP_EOL;  
        $data_to_write .= '// use Illuminate\Database\Console\Seeds\WithoutModelEvents;'.PHP_EOL;
        $data_to_write .= 'use Illuminate\Database\Seeder;'.PHP_EOL.PHP_EOL; 
        $data_to_write .= 'class DatabaseSeeder extends Seeder'.PHP_EOL;
        $data_to_write .= '{'.PHP_EOL;
        $data_to_write .= '    /**'.PHP_EOL;
        $data_to_write .= '     * Seed the application\'s database.'.PHP_EOL;
        $data_to_write .= '     */'.PHP_EOL;
        $data_to_write .= '    public function run(): void'.PHP_EOL;
        $data_to_write .= '    {'.PHP_EOL;
        $data_to_write .= '        $this->call(['.PHP_EOL;
        $data_to_write .= '              RoleSeeder::class'.PHP_EOL;
        $data_to_write .= '        ]);'.PHP_EOL;
        $data_to_write .= '    }'.PHP_EOL;
        $data_to_write .= '}';
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
        /*********************** INSTALL ADMIN DASHBOARD ***********************************/
        $result = Process::run('composer require jeroennoten/laravel-adminlte');
        $result = Process::run('php artisan adminlte:install');
        $result = Process::run('php artisan adminlte:install --only=main_views');
        /*********************** construir sql ***********************************************/
        $result = Process::run('php artisan route:cache');
        $result = Process::run('php artisan cache:clear');
        $result = Process::run('php artisan db:wipe');
        $result = Process::run('php artisan migrate:fresh --seed');
        $result = Process::run('php artisan route:cache');
        /*************************************************************************************/
        echo 'Autenticaciòn del sistema construido con éxito!!! (Rutas, Solicitud,Controller, Model.)';
        
    }
}