<?php

class AdminLte{
    public function index(){
        $file_handle = fopen(base_path()."\\database\\seeders\\DatabaseSeeder.php", 'w'); 
        $data_to_write = '<?php'.PHP_EOL.PHP_EOL;
        $data_to_write .= '<!DOCTYPE html>'.PHP_EOL;
        $data_to_write .= '<html lang="en"> '.PHP_EOL;
        $data_to_write .= '<head>'.PHP_EOL;
        $data_to_write .= '  <meta charset="utf-8">'.PHP_EOL;
        $data_to_write .= '  <meta name="viewport" content="width=device-width, initial-scale=1">'.PHP_EOL;
        $data_to_write .= '  <title>{{env(\'APP_NAME\')}} | Dashboard</title>'.PHP_EOL.PHP_EOL; 
        $data_to_write .= '  <!-- Google Font: Source Sans Pro -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">'.PHP_EOL;
        $data_to_write .= '  <!-- Font Awesome -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">'.PHP_EOL;
        $data_to_write .= '  <!-- Ionicons -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">'.PHP_EOL;
        $data_to_write .= '  <!-- Tempusdominus Bootstrap 4 -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">'.PHP_EOL;
        $data_to_write .= '  <!-- iCheck -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">'.PHP_EOL;
        $data_to_write .= '  <!-- JQVMap -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="plugins/jqvmap/jqvmap.min.css">'.PHP_EOL;
        $data_to_write .= '  <!-- Theme style -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="dist/css/adminlte.min.css">'.PHP_EOL;
        $data_to_write .= '  <!-- overlayScrollbars -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">'.PHP_EOL;
        $data_to_write .= '  <!-- Daterange picker -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="plugins/daterangepicker/daterangepicker.css">'.PHP_EOL;
        $data_to_write .= '  <!-- summernote -->'.PHP_EOL;
        $data_to_write .= '  <link rel="stylesheet" href="plugins/summernote/summernote-bs4.min.css">'.PHP_EOL;
        $data_to_write .= '</head>'.PHP_EOL;
        $data_to_write .= '<body class="hold-transition sidebar-mini layout-fixed">'.PHP_EOL;
        $data_to_write .= '  <div class="wrapper"> '.PHP_EOL;
        $data_to_write .= '    <!-- Preloader -->'.PHP_EOL;
        $data_to_write .= '    <div class="preloader flex-column justify-content-center align-items-center">'.PHP_EOL;
        $data_to_write .= '      <img class="animation__shake" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">'.PHP_EOL;
        $data_to_write .= '    </div>'.PHP_EOL;
        $data_to_write .= '  </div>'.PHP_EOL;
        $data_to_write .= '</body>'.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
    }
    public function index2(){
        //https://www.cursosdesarrolloweb.es/blog/adminlte-laravel
        //https://adminlte.io/docs/3.2/layout.html
        //dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed
        /***********************************************************************************/ 
        $file_handle = fopen(base_path()."\\resources\\views\\DatabaseSeeder.php", 'w'); 
        $data_to_write = '<nav class="main-header navbar navbar-expand navbar-white navbar-light">'.PHP_EOL;
        $data_to_write .= '    <!-- Left navbar links -->'.PHP_EOL;
        $data_to_write .= '    <ul class="navbar-nav">'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item">'.PHP_EOL;
        $data_to_write .= '        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>'.PHP_EOL;
        $data_to_write .= '      </li>'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item d-none d-sm-inline-block">'.PHP_EOL;
        $data_to_write .= '        <a href="index3.html" class="nav-link">Home</a>'.PHP_EOL;
        $data_to_write .= '      </li>'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item d-none d-sm-inline-block">'.PHP_EOL;
        $data_to_write .= '        <a href="#" class="nav-link">Contact</a>'.PHP_EOL;
        $data_to_write .= '      </li>'.PHP_EOL;
        $data_to_write .= '    </ul> '.PHP_EOL;
        $data_to_write .= '    <!-- Right navbar links -->'.PHP_EOL;
        $data_to_write .= '    <ul class="navbar-nav ml-auto">'.PHP_EOL;
        $data_to_write .= '      <!-- Navbar Search -->'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item">'.PHP_EOL;
        $data_to_write .= '        <a class="nav-link" data-widget="navbar-search" href="#" role="button">'.PHP_EOL;
        $data_to_write .= '        <i class="fas fa-search"></i>'.PHP_EOL;
        $data_to_write .= '        </a>'.PHP_EOL;
        $data_to_write .= '        <div class="navbar-search-block">'.PHP_EOL;
        $data_to_write .= '          <form class="form-inline">'.PHP_EOL;
        $data_to_write .= '            <div class="input-group input-group-sm">'.PHP_EOL;
        $data_to_write .= '              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">'.PHP_EOL;
        $data_to_write .= '              <div class="input-group-append">'.PHP_EOL;
        $data_to_write .= '                <button class="btn btn-navbar" type="submit">'.PHP_EOL;
        $data_to_write .= '                <i class="fas fa-search"></i>'.PHP_EOL;
        $data_to_write .= '                </button>'.PHP_EOL;
        $data_to_write .= '                <button class="btn btn-navbar" type="button" data-widget="navbar-search">'.PHP_EOL;
        $data_to_write .= '                <i class="fas fa-times"></i>'.PHP_EOL;
        $data_to_write .= '                </button>'.PHP_EOL;
        $data_to_write .= '              </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '          </form>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '      </li> '.PHP_EOL;
        $data_to_write .= '      <!-- Messages Dropdown Menu -->'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item dropdown">'.PHP_EOL;
        $data_to_write .= '        <a class="nav-link" data-toggle="dropdown" href="#">'.PHP_EOL;
        $data_to_write .= '          <i class="far fa-comments"></i>'.PHP_EOL;
        $data_to_write .= '          <span class="badge badge-danger navbar-badge">3</span>'.PHP_EOL;
        $data_to_write .= '        </a>'.PHP_EOL;
        $data_to_write .= '        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">'.PHP_EOL;
        $data_to_write .= '          <a href="#" class="dropdown-item">'.PHP_EOL;
        $data_to_write .= '            <!-- Message Start -->'.PHP_EOL;
        $data_to_write .= '             <div class="media">'.PHP_EOL;
        $data_to_write .= '              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">'.PHP_EOL;
        $data_to_write .= '              <div class="media-body">'.PHP_EOL;
        $data_to_write .= '                <h3 class="dropdown-item-title">'.PHP_EOL;
        $data_to_write .= '                Brad Diesel'.PHP_EOL;
        $data_to_write .= '                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>'.PHP_EOL;
        $data_to_write .= '                </h3>'.PHP_EOL;
        $data_to_write .= '                <p class="text-sm">Call me whenever you can...</p>'.PHP_EOL;
        $data_to_write .= '                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>'.PHP_EOL;
        $data_to_write .= '             </div>'.PHP_EOL;
        $data_to_write .= '           </div>'.PHP_EOL;
        $data_to_write .= '           <!-- Message End -->'.PHP_EOL;
        $data_to_write .= '          </a>'.PHP_EOL;
        $data_to_write .= '        <div class="dropdown-divider"></div>'.PHP_EOL;
        $data_to_write .= '        <a href="#" class="dropdown-item">'.PHP_EOL;
        $data_to_write .= '            <!-- Message Start -->'.PHP_EOL;
        $data_to_write .= '            <div class="media">'.PHP_EOL;
        $data_to_write .= '            <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">'.PHP_EOL;
        $data_to_write .= '            <div class="media-body">'.PHP_EOL;
        $data_to_write .= '                <h3 class="dropdown-item-title">'.PHP_EOL;
        $data_to_write .= '                John Pierce'.PHP_EOL;
        $data_to_write .= '                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>'.PHP_EOL;
        $data_to_write .= '                </h3>'.PHP_EOL;
        $data_to_write .= '                <p class="text-sm">I got your message bro</p>'.PHP_EOL;
        $data_to_write .= '                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <!-- Message End -->'.PHP_EOL;
        $data_to_write .= '        </a>'.PHP_EOL;
        $data_to_write .= '        <div class="dropdown-divider"></div>'.PHP_EOL;
        $data_to_write .= '        <a href="#" class="dropdown-item">'.PHP_EOL;
        $data_to_write .= '            <!-- Message Start -->'.PHP_EOL;
        $data_to_write .= '            <div class="media">'.PHP_EOL;
        $data_to_write .= '             <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">'.PHP_EOL;
        $data_to_write .= '             <div class="media-body">'.PHP_EOL;
        $data_to_write .= '                <h3 class="dropdown-item-title">'.PHP_EOL;
        $data_to_write .= '                Nora Silvester'.PHP_EOL;
        $data_to_write .= '                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>'.PHP_EOL;
        $data_to_write .= '                </h3>'.PHP_EOL;
        $data_to_write .= '                <p class="text-sm">The subject goes here</p>'.PHP_EOL;
        $data_to_write .= '                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>'.PHP_EOL;
        $data_to_write .= '             </div>'.PHP_EOL;
        $data_to_write .= '            </div>'.PHP_EOL;
        $data_to_write .= '            <!-- Message End -->'.PHP_EOL;
        $data_to_write .= '        </a>'.PHP_EOL;
        $data_to_write .= '        <div class="dropdown-divider"></div>'.PHP_EOL;
        $data_to_write .= '         <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '    </li>'.PHP_EOL;
        $data_to_write .= '    <!-- Notifications Dropdown Menu -->'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item dropdown">'.PHP_EOL;
        $data_to_write .= '        <a class="nav-link" data-toggle="dropdown" href="#">'.PHP_EOL;
        $data_to_write .= '         <i class="far fa-bell"></i>'.PHP_EOL;
        $data_to_write .= '         <span class="badge badge-warning navbar-badge">15</span>'.PHP_EOL;
        $data_to_write .= '        </a>'.PHP_EOL;
        $data_to_write .= '        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">'.PHP_EOL;
        $data_to_write .= '         <span class="dropdown-item dropdown-header">15 Notifications</span>'.PHP_EOL;
        $data_to_write .= '         <div class="dropdown-divider"></div>'.PHP_EOL;
        $data_to_write .= '         <a href="#" class="dropdown-item">'.PHP_EOL;
        $data_to_write .= '            <i class="fas fa-envelope mr-2"></i> 4 new messages'.PHP_EOL;
        $data_to_write .= '            <span class="float-right text-muted text-sm">3 mins</span>'.PHP_EOL;
        $data_to_write .= '         </a>'.PHP_EOL;
        $data_to_write .= '         <div class="dropdown-divider"></div>'.PHP_EOL;
        $data_to_write .= '         <a href="#" class="dropdown-item">'.PHP_EOL;
        $data_to_write .= '            <i class="fas fa-users mr-2"></i> 8 friend requests'.PHP_EOL;
        $data_to_write .= '            <span class="float-right text-muted text-sm">12 hours</span>'.PHP_EOL;
        $data_to_write .= '         </a>'.PHP_EOL;
        $data_to_write .= '         <div class="dropdown-divider"></div>'.PHP_EOL;
        $data_to_write .= '         <a href="#" class="dropdown-item">'.PHP_EOL;
        $data_to_write .= '            <i class="fas fa-file mr-2"></i> 3 new reports'.PHP_EOL;
        $data_to_write .= '            <span class="float-right text-muted text-sm">2 days</span>'.PHP_EOL;
        $data_to_write .= '         </a>'.PHP_EOL;
        $data_to_write .= '         <div class="dropdown-divider"></div>'.PHP_EOL;
        $data_to_write .= '         <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>'.PHP_EOL;
        $data_to_write .= '        </div>'.PHP_EOL;
        $data_to_write .= '      </li>'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item">'.PHP_EOL;
        $data_to_write .= '        <a class="nav-link" data-widget="fullscreen" href="#" role="button">'.PHP_EOL;
        $data_to_write .= '         <i class="fas fa-expand-arrows-alt"></i>'.PHP_EOL;
        $data_to_write .= '        </a>'.PHP_EOL;
        $data_to_write .= '      </li>'.PHP_EOL;
        $data_to_write .= '      <li class="nav-item">'.PHP_EOL;
        $data_to_write .= '        <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">'.PHP_EOL;
        $data_to_write .= '         <i class="fas fa-th-large"></i>'.PHP_EOL;
        $data_to_write .= '        </a>'.PHP_EOL;
        $data_to_write .= '      </li>'.PHP_EOL;
        $data_to_write .= '    </ul>'.PHP_EOL;
        $data_to_write .= '</nav>'.PHP_EOL;
        $data_to_write .= ''.PHP_EOL;
        fwrite($file_handle, $data_to_write);
        fclose($file_handle);
    } 
}